---

plugins: [jest]
# plugins: [flowtype]

env:
  node: true
  jest: true
  jasmine: true

parser: babel-eslint


extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings

rules:
  no-console: 0